builders:
  firestoreBuilder:
    import: "package:firebase/firestore/odm/builders/firestore_builder.dart"
    builder_factories: ["firestoreBuilder"]
    build_extensions: {".dart": [".odm.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]