name: firebase
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-323.2.beta

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  dart_casing: ^3.0.1
  dart_jsonwebtoken: ^2.14.0
  googleapis: ^13.2.0
  http: ^1.2.2
  build: ^2.4.1
  source_gen: ^1.5.0
  json_diff: ^0.2.1
  fast_immutable_collections: ^10.2.4
  uuid: ^4.4.2
  cloud_firestore: ^5.0.1
  meta: ^1.15.0
  googleapis_auth: ^1.6.0
  json_annotation: ^4.9.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
